### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rubik** [ashleysommer/pynecktie#1]
Hi, great idea. The lack of a project direction and updates on Sanic is a problem for my team as well.

I don't really know about the internals of uvloop and web frameworks, but I can contribute in some other ways. For example, can we just start by taking Sanic's documentation and replace all occurrences of the word "Sanic" with "Necktie" and replacing all links? Then we can think about improving the documentation (I think it's pretty scarce at the moment).

**Comment by ashleysommer** [comment]
@rubik 
Thanks for the support! I'm glad someone else likes my idea.

Yes, if you can contribute by taking the Sanic documentation and replacing all instances of the word "Sanic" with "Necktie", then opening a PR on this repository, that would be greatly appreciated.
